[package]
authors = ["hill <hill@hilll.dev>"]
description = "a rust port of music21 (for now just the chord naming algorithm)"
edition = "2021"
keywords = ["music", "chords", "music21"]
license = "LICENSE"
name = "music21-rs"
repository = "https://github.com/float3/music21-rs"
version = "0.0.1"
# build = "build.rs"

[dependencies]
fraction = "0.15.3"
itertools = "0.14.0"
num = "0.4.3"
num-traits = "0.2.19"
ordered-float = "4.6.0"

[build-dependencies]
pyo3 = { version = "0.23.4", features = ["auto-initialize"] }
