[package]
authors = ["hill <hill@hilll.dev>"]
build = "build.rs"
description = "a rust port of music21 (for now just the chord naming algorithm)"
edition = "2021"
include = ["/src", "/utils", "build.rs", "music21/music21/chord/tables.py"]
keywords = ["music", "chords", "music21"]
license-file = "LICENSE"
name = "music21-rs"
repository = "https://github.com/float3/music21-rs"
version = "0.0.2"

[workspace]
members = ["utils"]

[features]
default = ["serde"]
python = ["dep:pyo3", "utils/python"]
serde = ["dep:serde"]
# halfprecision = []

[dependencies]
fraction = "0.15.3"
itertools = "0.14.0"
num = "0.4.3"
num-traits = "0.2.19"
ordered-float = "5.0.0"
regex = "1.11.1"
serde = { version = "1.0.217", optional = true, features = ["derive"] }

[build-dependencies]
pyo3 = { version = "0.23.4", features = ["auto-initialize"], optional = true }
utils = { path = "./utils", default-features = false }

[dev-dependencies]
pyo3 = { version = "0.23.4", features = ["auto-initialize"] }
rodio = "0.20.1"
utils = { path = "./utils" }
