[package]
authors = ["hill <hill@hilll.dev>"]
build = "build.rs"
description = "a rust port of music21 (for now just the chord naming algorithm)"
edition = "2024"
include = ["/src", "./utils/src/lib.rs", "build.rs", "/examples", "shared.rs"]
keywords = ["music", "chords", "music21"]
license-file = "LICENSE"
name = "music21-rs"
repository = "https://github.com/float3/music21-rs"
version = "0.0.3"

[workspace]
members = ["utils"]

[features]
default = ["serde"]
python = ["dep:pyo3", "dep:reqwest", "dep:sha2"]
serde = ["dep:serde"]

[dependencies]
fraction = "0.15.3"
itertools = "0.14.0"
num = "0.4.3"
num-traits = "0.2.19"
ordered-float = "5.0.0"
regex = "1.11.1"
serde = { version = "1.0.219", optional = true, features = ["derive"] }

[build-dependencies]
pyo3 = { version = "0.24.1", features = ["auto-initialize"], optional = true }
reqwest = { version = "0.12.15", features = ["blocking"], optional = true }
sha2 = { version = "0.10.8", optional = true }

[dev-dependencies]
pyo3 = { version = "0.24.1", features = ["auto-initialize"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
sha2 = { version = "0.10.8" }
rodio = "0.20.1"
