//! Checks [`Harte`] against what harte-library makes of every label in its
//! own coverage set, on music21.
//!
//! `data/harte_expectations.toml` records, for each of the 8,064 labels the
//! library's tests cover, the pitches, root, bass, sounding degrees and
//! prettified spelling the library builds, or the exception it raises. It is
//! generated by `cargo run --release -p xtask --features python --
//! regenerate-fixtures` from the pinned harte-library checkout, so this test
//! needs neither Python nor the checkout.

use std::path::Path;

use music21_rs::harte::degree_sort_key;
use music21_rs::{Harte, Pitch};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Expectations {
    chord: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    label: String,
    #[serde(default)]
    pitches: Vec<String>,
    root: Option<String>,
    bass: Option<String>,
    #[serde(default)]
    degrees: Vec<String>,
    pretty: Option<String>,
    error: Option<String>,
}

fn expectations() -> Expectations {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(|root| root.join("data/harte_expectations.toml"))
        .unwrap_or_default();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("{} is unreadable: {err}", path.display()));
    toml::from_str(&text).expect("harte expectations parse")
}

/// `C:maj7(#11,9)` with the degrees in its parentheses sorted, as the
/// fixture writes them.
fn sort_parenthesised(label: &str) -> String {
    let Some((head, rest)) = label.split_once('(') else {
        return label.to_string();
    };
    let Some((inside, tail)) = rest.split_once(')') else {
        return label.to_string();
    };
    let mut degrees: Vec<&str> = inside.split(',').collect();
    degrees.sort_unstable();
    format!("{head}({}){tail}", degrees.join(","))
}

/// Degrees and the pitches they sound, in the library's degree order with
/// its ties broken by spelling. The library breaks them by set order, which
/// is not fixed from one run to the next, so `A:min6/bb3` may put `bb3`
/// either side of `b3`.
fn in_degree_order(degrees: &[String], pitches: &[String]) -> Vec<(String, String)> {
    let mut pairs: Vec<(String, String)> = degrees
        .iter()
        .cloned()
        .zip(pitches.iter().cloned())
        .collect();
    pairs.sort_by(|a, b| {
        degree_sort_key(&a.0)
            .partial_cmp(&degree_sort_key(&b.0))
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.0.cmp(&b.0))
    });
    pairs
}

#[test]
fn every_label_in_harte_librarys_coverage_set_builds_the_same_chord() {
    let expectations = expectations();
    assert_eq!(expectations.chord.len(), 8064, "the coverage set");
    let refused = expectations
        .chord
        .iter()
        .filter(|case| case.error.is_some())
        .count();
    assert_eq!(refused, 212, "the labels the library's own grammar refuses");

    let mut mismatches = Vec::new();
    for case in &expectations.chord {
        let harte = match (Harte::new(&case.label), &case.error) {
            (Err(_), Some(_)) => continue,
            (Ok(_), Some(error)) => {
                mismatches.push(format!(
                    "{}: built, but the library raises {error}",
                    case.label
                ));
                continue;
            }
            (Err(err), None) => {
                mismatches.push(format!("{}: {err}", case.label));
                continue;
            }
            (Ok(harte), None) => harte,
        };
        let pitches: Vec<String> = harte
            .chord()
            .pitches()
            .iter()
            .map(Pitch::name_with_octave)
            .collect();
        let root = harte.chord().root().map(Pitch::name_with_octave);
        let bass = harte.chord().bass().map(Pitch::name_with_octave);
        let pretty = sort_parenthesised(&harte.prettify());
        let got = (
            in_degree_order(harte.sounding_degrees(), &pitches),
            root,
            bass,
            Some(pretty),
        );
        let want = (
            in_degree_order(&case.degrees, &case.pitches),
            case.root.clone(),
            case.bass.clone(),
            case.pretty.clone(),
        );
        if got != want {
            mismatches.push(format!(
                "{}:\n    got  {got:?}\n    want {want:?}",
                case.label
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} labels differ from harte-library:\n{}",
        mismatches.len(),
        expectations.chord.len(),
        mismatches.join("\n")
    );
}
