//! Checks [`TimeSignature`] against what music21's `meter` package produces.
//!
//! The crate derives every one of these properties from the numerator and
//! denominator alone. music21 derives them from a `MeterSequence` partition
//! tree that also drives beaming and accent weighting. This test is what proves
//! the shortcut agrees with the tree across the meters people actually write.
//!
//! `data/meter_expectations.toml` is generated by
//! `cargo run -p xtask --features python -- regenerate-fixtures` and committed, so this test
//! needs neither Python nor the submodule.

use music21_rs::TimeSignature;
use serde::Deserialize;

use std::path::Path;

#[derive(Debug, Deserialize)]
struct Expectations {
    meter: Vec<MeterExpectation>,
}

#[derive(Debug, Deserialize)]
struct MeterExpectation {
    ratio: String,
    bar_quarter_length: f64,
    beat_count: u32,
    beat_quarter_length: f64,
    beat_division_count: u32,
    beat_count_name: String,
    beat_division_count_name: String,
    classification: String,
    beat_offsets: Vec<f64>,
}

fn expectations() -> Expectations {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("python-parity has a parent directory")
        .join("data/meter_expectations.toml");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("{} is unreadable: {err}", path.display()));
    toml::from_str(&text).expect("meter expectations parse")
}

/// music21 reports quarter lengths as exact fractions; the crate uses `f64`.
fn close(actual: f64, expected: f64) -> bool {
    (actual - expected).abs() < 1e-9
}

#[test]
fn every_time_signature_matches_music21() {
    let mut mismatches = Vec::new();

    for expected in &expectations().meter {
        let actual = TimeSignature::from_ratio_string(&expected.ratio)
            .unwrap_or_else(|err| panic!("{} should parse: {err}", expected.ratio));
        let ratio = &expected.ratio;

        let mut check = |field: &str, actual: String, wanted: String| {
            if actual != wanted {
                mismatches.push(format!("{ratio} {field}: music21 {wanted}, crate {actual}"));
            }
        };

        check(
            "beat_count",
            actual.beat_count().to_string(),
            expected.beat_count.to_string(),
        );
        check(
            "beat_division_count",
            actual.beat_division_count().to_string(),
            expected.beat_division_count.to_string(),
        );
        check(
            "beat_count_name",
            actual.beat_count_name(),
            expected.beat_count_name.clone(),
        );
        check(
            "beat_division_count_name",
            actual.beat_division().music21_name().to_string(),
            expected.beat_division_count_name.clone(),
        );
        check(
            "classification",
            actual.classification(),
            expected.classification.clone(),
        );

        if !close(actual.bar_quarter_length(), expected.bar_quarter_length) {
            mismatches.push(format!(
                "{ratio} bar_quarter_length: music21 {}, crate {}",
                expected.bar_quarter_length,
                actual.bar_quarter_length()
            ));
        }
        if !close(actual.beat_quarter_length(), expected.beat_quarter_length) {
            mismatches.push(format!(
                "{ratio} beat_quarter_length: music21 {}, crate {}",
                expected.beat_quarter_length,
                actual.beat_quarter_length()
            ));
        }

        let offsets = actual.beat_offsets();
        if offsets.len() != expected.beat_offsets.len()
            || !offsets
                .iter()
                .zip(&expected.beat_offsets)
                .all(|(a, b)| close(*a, *b))
        {
            mismatches.push(format!(
                "{ratio} beat_offsets: music21 {:?}, crate {offsets:?}",
                expected.beat_offsets
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} time signatures differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}

#[test]
fn the_fixture_covers_both_simple_and_compound_meters() {
    let expectations = expectations();
    assert!(
        expectations.meter.len() >= 100,
        "fixture should sweep a wide grid, got {}",
        expectations.meter.len()
    );

    for wanted in ["Simple", "Compound", "Other"] {
        assert!(
            expectations
                .meter
                .iter()
                .any(|entry| entry.beat_division_count_name == wanted),
            "fixture is missing every {wanted} meter"
        );
    }
}
