//! Checks the tone-row tables transcribed from music21's `serial` module.
//!
//! The 71 historical rows are typed into `src/serial.rs` by hand, and the Link
//! chord catalogue is a table of 238 interval strings inside a music21 method
//! body. `data/serial_expectations.toml` is generated by
//! `cargo run -p xtask --features python -- regenerate-fixtures` and committed,
//! so this test needs neither Python nor the submodule; `fixture_freshness.rs`
//! keeps the fixture itself honest against a bumped submodule.

use music21_rs::{HISTORICAL_ROWS, ToneRow, historical_row_by_name};
use serde::Deserialize;

use std::path::Path;

#[derive(Debug, Deserialize)]
struct Expectations {
    historical_row: Vec<HistoricalRowExpectation>,
    link_chord: Vec<LinkChordExpectation>,
}

#[derive(Debug, Deserialize)]
struct HistoricalRowExpectation {
    name: String,
    composer: String,
    opus: Option<String>,
    title: String,
    pitch_classes: Vec<u8>,
    intervals: String,
    is_all_interval: bool,
    link_classification: Option<u32>,
    link_special_intervals: Vec<String>,
    matrix: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct LinkChordExpectation {
    intervals: String,
    pitch_classes: Vec<u8>,
    classification: Option<u32>,
    special_intervals: Vec<String>,
}

fn expectations() -> Expectations {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("python-parity has a parent directory")
        .join("data/serial_expectations.toml");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("{} is unreadable: {err}", path.display()));
    toml::from_str(&text).expect("serial expectations parse")
}

fn classification(row: &ToneRow) -> (Option<u32>, Vec<String>) {
    match row
        .link_classification()
        .expect("a historical row is twelve-tone")
    {
        Some(link) => (
            Some(link.number),
            link.special_intervals
                .iter()
                .map(|value| value.to_string())
                .collect(),
        ),
        None => (None, Vec::new()),
    }
}

#[test]
fn historical_rows_match_music21() {
    let expectations = expectations();
    assert_eq!(
        expectations.historical_row.len(),
        HISTORICAL_ROWS.len(),
        "music21 ships {} historical rows, the crate {}",
        expectations.historical_row.len(),
        HISTORICAL_ROWS.len()
    );

    let mut mismatches = Vec::new();
    for expected in &expectations.historical_row {
        let actual = match historical_row_by_name(&expected.name) {
            Ok(row) => row,
            Err(error) => {
                mismatches.push(format!("{}: unknown to the crate ({error})", expected.name));
                continue;
            }
        };
        if actual.composer != expected.composer {
            mismatches.push(format!(
                "{} composer: music21 {:?}, crate {:?}",
                expected.name, expected.composer, actual.composer
            ));
        }
        if actual.opus != expected.opus.as_deref() {
            mismatches.push(format!(
                "{} opus: music21 {:?}, crate {:?}",
                expected.name, expected.opus, actual.opus
            ));
        }
        if actual.title != expected.title {
            mismatches.push(format!(
                "{} title: music21 {:?}, crate {:?}",
                expected.name, expected.title, actual.title
            ));
        }
        if actual.pitch_classes != expected.pitch_classes.as_slice() {
            mismatches.push(format!(
                "{} row: music21 {:?}, crate {:?}",
                expected.name, expected.pitch_classes, actual.pitch_classes
            ));
        }

        let row = actual.row();
        if row.intervals_as_string() != expected.intervals {
            mismatches.push(format!(
                "{} intervals: music21 {:?}, crate {:?}",
                expected.name,
                expected.intervals,
                row.intervals_as_string()
            ));
        }
        if row.is_all_interval().unwrap() != expected.is_all_interval {
            mismatches.push(format!(
                "{} all-interval: music21 {}, crate {}",
                expected.name,
                expected.is_all_interval,
                row.is_all_interval().unwrap()
            ));
        }
        let (number, special) = classification(&row);
        if number != expected.link_classification || special != expected.link_special_intervals {
            mismatches.push(format!(
                "{} link chord: music21 {:?} {:?}, crate {number:?} {special:?}",
                expected.name, expected.link_classification, expected.link_special_intervals
            ));
        }
        let expected_matrix = expected.matrix.join("\n");
        if row.matrix().to_string() != expected_matrix {
            mismatches.push(format!(
                "{} matrix:\nmusic21\n{expected_matrix}\ncrate\n{}",
                expected.name,
                row.matrix()
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} historical row values differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}

#[test]
fn link_chords_match_music21() {
    let expectations = expectations();
    assert!(
        expectations.link_chord.len() >= 238,
        "expected music21's full Link chord catalogue, found {}",
        expectations.link_chord.len()
    );

    let mut mismatches = Vec::new();
    for expected in &expectations.link_chord {
        let row = ToneRow::from(expected.pitch_classes.clone());
        let (number, special) = classification(&row);
        if number != expected.classification || special != expected.special_intervals {
            mismatches.push(format!(
                "{}: music21 {:?} {:?}, crate {number:?} {special:?}",
                expected.intervals, expected.classification, expected.special_intervals
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} Link chords classify differently from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}
