//! Checks the small music21 tables the crate transcribes by hand.
//!
//! `chord/tables.py` and the Scala tuning tables are *generated*, so drift is
//! impossible by construction. These are not: they are small enough that
//! someone typed them in, which is exactly how they rot unnoticed. Two
//! mistranscribed Partch ratios shipped and passed CI for precisely that
//! reason.
//!
//! `data/table_expectations.toml` is generated by
//! `cargo run -p xtask --features python -- regenerate-fixtures` and committed, so this test
//! needs neither Python nor the submodule. `fixture_freshness.rs` is what stops
//! the fixture itself going stale against a bumped submodule.

use music21_rs::{Accidental, DEFAULT_TEMPO_VALUES, Interval, KeyProfile, key};
use serde::Deserialize;

use std::path::Path;

#[derive(Debug, Deserialize)]
struct Expectations {
    accidental: Vec<AccidentalExpectation>,
    mode: Vec<ModeExpectation>,
    specifier: Vec<SpecifierExpectation>,
    key_profile: Vec<KeyProfileExpectation>,
    tempo: Vec<TempoExpectation>,
}

#[derive(Debug, Deserialize)]
struct TempoExpectation {
    name: String,
    number: f64,
}

#[derive(Debug, Deserialize)]
struct KeyProfileExpectation {
    name: String,
    mode: String,
    weights: Vec<f64>,
}

#[derive(Debug, Deserialize)]
struct AccidentalExpectation {
    name: String,
    modifier: String,
    alter: f64,
    unicode: String,
}

#[derive(Debug, Deserialize)]
struct ModeExpectation {
    name: String,
    sharps_alter: i32,
}

#[derive(Debug, Deserialize)]
struct SpecifierExpectation {
    prefix: String,
    number: i32,
    semitones: i32,
}

fn expectations() -> Expectations {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("python-parity has a parent directory")
        .join("data/table_expectations.toml");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("{} is unreadable: {err}", path.display()));
    toml::from_str(&text).expect("table expectations parse")
}

#[test]
fn accidentals_match_music21() {
    let mut mismatches = Vec::new();

    for expected in &expectations().accidental {
        let actual = match Accidental::new(expected.name.as_str()) {
            Ok(accidental) => accidental,
            Err(error) => {
                mismatches.push(format!("{}: does not construct ({error})", expected.name));
                continue;
            }
        };

        if actual.modifier() != expected.modifier {
            mismatches.push(format!(
                "{} modifier: music21 {:?}, crate {:?}",
                expected.name,
                expected.modifier,
                actual.modifier()
            ));
        }
        if (actual.alter() - expected.alter).abs() > 1e-9 {
            mismatches.push(format!(
                "{} alter: music21 {}, crate {}",
                expected.name,
                expected.alter,
                actual.alter()
            ));
        }
        if actual.unicode() != expected.unicode {
            mismatches.push(format!(
                "{} unicode: music21 {:?}, crate {:?}",
                expected.name,
                expected.unicode,
                actual.unicode()
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} accidental values differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}

#[test]
fn every_music21_accidental_name_is_known_to_the_crate() {
    let known = Accidental::list_names();
    for expected in &expectations().accidental {
        assert!(
            known.contains(&expected.name.as_str()),
            "{} is missing from Accidental::list_names()",
            expected.name
        );
    }
}

#[test]
fn mode_sharps_alter_matches_music21() {
    let mut mismatches = Vec::new();

    for expected in &expectations().mode {
        match key::mode_sharps_alter(&expected.name) {
            Some(actual) if actual == expected.sharps_alter => {}
            Some(actual) => mismatches.push(format!(
                "{}: music21 {}, crate {actual}",
                expected.name, expected.sharps_alter
            )),
            None => mismatches.push(format!("{}: unknown to the crate", expected.name)),
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} modes differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}

#[test]
fn interval_specifiers_match_music21() {
    let mut mismatches = Vec::new();

    for expected in &expectations().specifier {
        let name = format!("{}{}", expected.prefix, expected.number);
        match Interval::from_name(name.as_str()) {
            Ok(interval) if interval.semitones() == expected.semitones => {}
            Ok(interval) => mismatches.push(format!(
                "{name}: music21 {} semitones, crate {}",
                expected.semitones,
                interval.semitones()
            )),
            Err(error) => mismatches.push(format!("{name}: does not parse ({error})")),
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} interval specifiers differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}

#[test]
fn key_profiles_match_music21() {
    let expectations = expectations();
    let mut mismatches = Vec::new();
    let mut seen = std::collections::BTreeSet::new();

    for expected in &expectations.key_profile {
        let Some(profile) = KeyProfile::ALL
            .into_iter()
            .find(|profile| profile.music21_class_name() == expected.name)
        else {
            mismatches.push(format!("{}: unknown to the crate", expected.name));
            continue;
        };
        seen.insert(profile);
        let actual = match expected.mode.as_str() {
            "major" => profile.major_weights(),
            "minor" => profile.minor_weights(),
            other => {
                mismatches.push(format!("{}: unexpected mode {other:?}", expected.name));
                continue;
            }
        };
        if actual.len() != expected.weights.len()
            || actual
                .iter()
                .zip(&expected.weights)
                .any(|(left, right)| (left - right).abs() > 1e-9)
        {
            mismatches.push(format!(
                "{} {}: music21 {:?}, crate {:?}",
                expected.name, expected.mode, expected.weights, actual
            ));
        }
    }

    for profile in KeyProfile::ALL {
        if !seen.contains(&profile) {
            mismatches.push(format!("{profile:?}: not in music21's keyWeightKeyAnalysisClasses"));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} key profile values differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}

#[test]
fn tempo_words_match_music21() {
    let expectations = expectations();
    let mut mismatches = Vec::new();

    if expectations.tempo.len() != DEFAULT_TEMPO_VALUES.len() {
        mismatches.push(format!(
            "music21 has {} tempo words, the crate {}",
            expectations.tempo.len(),
            DEFAULT_TEMPO_VALUES.len()
        ));
    }
    for (position, expected) in expectations.tempo.iter().enumerate() {
        match DEFAULT_TEMPO_VALUES.get(position) {
            Some((name, number)) if *name == expected.name && *number == expected.number => {}
            Some((name, number)) => mismatches.push(format!(
                "position {position}: music21 {} = {}, crate {name} = {number}",
                expected.name, expected.number
            )),
            None => mismatches.push(format!("{}: missing from the crate", expected.name)),
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} tempo values differ from music21:\n    {}",
        mismatches.len(),
        mismatches.join("\n    ")
    );
}
