//! Checks `iterate_all_voice_leading_quartets` against what music21 finds in
//! its own corpus.
//!
//! `data/voice_leading_expectations.toml` carries each part of a few scores
//! as its flattened elements, and every quartet music21's
//! `iterateAllVoiceLeadingQuartets` gives under four settings of its keyword
//! arguments. It is generated by
//! `cargo run --release -p xtask --features python -- regenerate-fixtures`
//! and committed, so this test needs neither Python nor the submodule.
//!
//! The quartets are compared sorted, with the two voices of each sorted too.
//! music21 orders the voices within one offset by a counter of when each note
//! object was inserted into its stream, which a score built here has no
//! counterpart for; which quartets there are is the musical question.

use music21_rs::{
    Chord, Duration, MetronomeMark, Note, Pitch, QuartetOptions, Rest, Stream, StreamKind,
    iterate_all_voice_leading_quartets,
};
use serde::Deserialize;

use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct Expectations {
    score: Vec<Score>,
}

#[derive(Debug, Deserialize)]
struct Score {
    name: String,
    parts: Vec<Vec<String>>,
    run: Vec<Run>,
}

#[derive(Debug, Deserialize)]
struct Run {
    include_rests: bool,
    include_oblique: bool,
    include_no_motion: bool,
    quartets: Vec<String>,
}

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("data/voice_leading_expectations.toml")
}

/// One score as the crate holds one: parts of notes, chords and rests.
fn build(score: &Score) -> Stream {
    let mut built = Stream::with_kind(StreamKind::Score);
    for elements in &score.parts {
        let mut part = Stream::with_kind(StreamKind::Part);
        for element in elements {
            let fields: Vec<&str> = element.splitn(4, '|').collect();
            let [offset, length, kind, what] = fields[..] else {
                panic!("{}: malformed element {element:?}", score.name);
            };
            let offset: f64 = offset.parse().expect("an offset");
            let duration = Duration::new(length.parse().expect("a length")).expect("a duration");
            match kind {
                "n" => {
                    let pitch = Pitch::from_name(what).expect("a pitch");
                    part.insert(offset, Note::from_pitch(pitch).with_duration(duration));
                }
                "c" => {
                    let chord = Chord::new(what).expect("a chord");
                    part.insert(offset, chord.with_duration(duration));
                }
                "r" => part.insert(offset, Rest::new(duration)),
                "o" => {
                    let order: f64 = what.parse().expect("a classSortOrder");
                    if order < 20.0 {
                        // A clef, a barline, an instrument: the crate holds
                        // none of them, and all that matters of one is that
                        // it stands here and sorts ahead of a note, which a
                        // metronome mark does too.
                        part.insert(offset, MetronomeMark::new(60.0));
                    } else {
                        // Spanners, which music21 keeps at the very start of
                        // a part where no voice has anything to come from.
                        assert_eq!(offset, 0.0, "{}: {element:?}", score.name);
                    }
                }
                other => panic!("{}: unknown element kind {other:?}", score.name),
            }
        }
        built.insert(0.0, part);
    }
    built
}

/// Quartets music21 gives that are not in the music, by score.
///
/// The Schoenberg has a triplet F#3 running from 27 2/3 to 28 1/3, followed
/// by an E-3. music21 adds the offset and the length as floats, the sum comes
/// out a hair past the E-3's own offset, and so it reads the F#3 as still
/// sounding when the E-3 starts and pairs the voice with itself. The crate
/// allows offsets that hair of latitude and does not.
const FLOAT_ARTIFACTS: [(&str, &str); 1] = [("schoenberg/opus19/movement6", "F#3 E-3|F#3 F#3")];

/// A quartet with its voices in a fixed order, since which voice is named
/// first is part of the ordering this test leaves out.
fn normalized(quartet: &str) -> String {
    let mut voices: Vec<&str> = quartet.split('|').collect();
    voices.sort_unstable();
    voices.join("|")
}

#[test]
fn the_quartets_of_a_score_are_the_ones_music21_finds() {
    let text = std::fs::read_to_string(fixture_path()).expect("the voice-leading fixture");
    let expectations: Expectations = toml::from_str(&text).expect("a well-formed fixture");
    assert!(!expectations.score.is_empty());

    let mut compared = 0;
    let mut artifacts_met = 0;
    for score in &expectations.score {
        let built = build(score);
        for run in &score.run {
            let options = QuartetOptions {
                include_rests: run.include_rests,
                include_oblique: run.include_oblique,
                include_no_motion: run.include_no_motion,
            };
            let mut ours: Vec<String> = iterate_all_voice_leading_quartets(&built, options)
                .expect("quartets")
                .iter()
                .map(|quartet| {
                    normalized(&format!(
                        "{} {}|{} {}",
                        quartet.v1n1().name_with_octave(),
                        quartet.v1n2().name_with_octave(),
                        quartet.v2n1().name_with_octave(),
                        quartet.v2n2().name_with_octave(),
                    ))
                })
                .collect();
            let mut theirs: Vec<String> = run
                .quartets
                .iter()
                .filter(|quartet| {
                    let artifact = FLOAT_ARTIFACTS
                        .iter()
                        .any(|(name, listed)| *name == score.name && listed == quartet);
                    artifacts_met += usize::from(artifact);
                    !artifact
                })
                .map(|quartet| normalized(quartet))
                .collect();
            ours.sort_unstable();
            theirs.sort_unstable();
            assert_eq!(
                ours.len(),
                theirs.len(),
                "{} under {options:?}: how many quartets",
                score.name
            );
            assert_eq!(ours, theirs, "{} under {options:?}", score.name);
            compared += theirs.len();
        }
    }
    // The chorale alone has some hundreds; a fixture that lost its quartets
    // would otherwise pass by comparing nothing.
    assert!(compared > 4000, "only {compared} quartets were compared");
    // A listed artifact music21 no longer gives should come off the list.
    assert!(artifacts_met > 0, "no listed float artifact was met");
}
