// @generated by `cargo run -p xtask -- emit-tuning-tables`.
// Source of truth: data/tuning_tables.toml. Do not edit by hand.

use super::Fraction;

/// Twelve-tone just intonation ratios.
///
/// Derived from `carlos_harm.scl` in music21's Scala archive: Carlos Harmonic & Ben Johnston's scale of 'Blues' from Suite f.micr.piano (1977) & David Beardsley's scale of 'Science Friction'
pub const JUST_INTONATION: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new(17, 16),
    Fraction::new(9, 8),
    Fraction::new(19, 16),
    Fraction::new(5, 4),
    Fraction::new(21, 16),
    Fraction::new(11, 8),
    Fraction::new(3, 2),
    Fraction::new(13, 8),
    Fraction::new(27, 16),
    Fraction::new(7, 4),
    Fraction::new(15, 8),
];

/// Twenty-four-tone just intonation ratios.
pub const JUST_INTONATION_24: [Fraction; 24] = [
    Fraction::new(1, 1),
    Fraction::new(33, 32),
    Fraction::new(17, 16),
    Fraction::new(35, 32),
    Fraction::new(9, 8),
    Fraction::new(37, 32),
    Fraction::new(19, 16),
    Fraction::new(39, 32),
    Fraction::new(5, 4),
    Fraction::new(21, 16),
    Fraction::new(43, 32),
    Fraction::new(11, 8),
    Fraction::new(45, 32),
    Fraction::new(23, 16),
    Fraction::new(3, 2),
    Fraction::new(25, 16),
    Fraction::new(51, 32),
    Fraction::new(13, 8),
    Fraction::new(27, 16),
    Fraction::new(7, 4),
    Fraction::new(57, 32),
    Fraction::new(29, 16),
    Fraction::new(15, 8),
    Fraction::new(31, 16),
];

/// Twelve-tone Pythagorean tuning ratios.
pub const PYTHAGOREAN_TUNING: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new(256, 243),
    Fraction::new(9, 8),
    Fraction::new(32, 27),
    Fraction::new(81, 64),
    Fraction::new(4, 3),
    Fraction::new(729, 512),
    Fraction::new(3, 2),
    Fraction::new(128, 81),
    Fraction::new(27, 16),
    Fraction::new(16, 9),
    Fraction::new(243, 128),
];

/// Twelve-tone five-limit tuning ratios.
///
/// Derived from `riley_albion.scl` in music21's Scala archive: Terry Riley's Harp of New Albion scale, inverse Malcolm's Monochord, 1/1 on C#
pub const FIVE_LIMIT: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new(16, 15),
    Fraction::new(9, 8),
    Fraction::new(6, 5),
    Fraction::new(5, 4),
    Fraction::new(4, 3),
    Fraction::new(64, 45),
    Fraction::new(3, 2),
    Fraction::new(8, 5),
    Fraction::new(5, 3),
    Fraction::new(16, 9),
    Fraction::new(15, 8),
];

/// Twenty-nine-tone eleven-limit tuning ratios.
///
/// Derived from `partch_29.scl` in music21's Scala archive: Partch/Ptolemy 11-limit Diamond
pub const ELEVEN_LIMIT: [Fraction; 29] = [
    Fraction::new(1, 1),
    Fraction::new(12, 11),
    Fraction::new(11, 10),
    Fraction::new(10, 9),
    Fraction::new(9, 8),
    Fraction::new(8, 7),
    Fraction::new(7, 6),
    Fraction::new(6, 5),
    Fraction::new(11, 9),
    Fraction::new(5, 4),
    Fraction::new(14, 11),
    Fraction::new(9, 7),
    Fraction::new(4, 3),
    Fraction::new(11, 8),
    Fraction::new(7, 5),
    Fraction::new(10, 7),
    Fraction::new(16, 11),
    Fraction::new(3, 2),
    Fraction::new(14, 9),
    Fraction::new(11, 7),
    Fraction::new(8, 5),
    Fraction::new(18, 11),
    Fraction::new(5, 3),
    Fraction::new(12, 7),
    Fraction::new(7, 4),
    Fraction::new(16, 9),
    Fraction::new(9, 5),
    Fraction::new(20, 11),
    Fraction::new(11, 6),
];

/// Forty-three-tone tuning ratios.
///
/// Derived from `partch_43.scl` in music21's Scala archive: Harry Partch's 43-tone pure scale
pub const FORTY_THREE_TONE: [Fraction; 43] = [
    Fraction::new(1, 1),
    Fraction::new(81, 80),
    Fraction::new(33, 32),
    Fraction::new(21, 20),
    Fraction::new(16, 15),
    Fraction::new(12, 11),
    Fraction::new(11, 10),
    Fraction::new(10, 9),
    Fraction::new(9, 8),
    Fraction::new(8, 7),
    Fraction::new(7, 6),
    Fraction::new(32, 27),
    Fraction::new(6, 5),
    Fraction::new(11, 9),
    Fraction::new(5, 4),
    Fraction::new(14, 11),
    Fraction::new(9, 7),
    Fraction::new(21, 16),
    Fraction::new(4, 3),
    Fraction::new(27, 20),
    Fraction::new(11, 8),
    Fraction::new(7, 5),
    Fraction::new(10, 7),
    Fraction::new(16, 11),
    Fraction::new(40, 27),
    Fraction::new(3, 2),
    Fraction::new(32, 21),
    Fraction::new(14, 9),
    Fraction::new(11, 7),
    Fraction::new(8, 5),
    Fraction::new(18, 11),
    Fraction::new(5, 3),
    Fraction::new(27, 16),
    Fraction::new(12, 7),
    Fraction::new(7, 4),
    Fraction::new(16, 9),
    Fraction::new(9, 5),
    Fraction::new(20, 11),
    Fraction::new(11, 6),
    Fraction::new(15, 8),
    Fraction::new(40, 21),
    Fraction::new(64, 33),
    Fraction::new(160, 81),
];

/// Seven-tone Indian scale ratios.
///
/// Derived from `ptolemy.scl` in music21's Scala archive: Intense Diatonic Syntonon, also Zarlino's scale
pub const INDIAN_SCALE: [Fraction; 7] = [
    Fraction::new(1, 1),
    Fraction::new(9, 8),
    Fraction::new(5, 4),
    Fraction::new(4, 3),
    Fraction::new(3, 2),
    Fraction::new(5, 3),
    Fraction::new(15, 8),
];

/// Alternate seven-tone Indian scale ratios.
///
/// Derived from `indian-sagrama.scl` in music21's Scala archive: Indian mode Sa-grama (Sa Ri Ga Ma Pa Dha Ni Sa), inverse of Didymus' diatonic
pub const INDIA_SCALE_ALT: [Fraction; 7] = [
    Fraction::new(1, 1),
    Fraction::new(9, 8),
    Fraction::new(5, 4),
    Fraction::new(4, 3),
    Fraction::new(3, 2),
    Fraction::new(27, 16),
    Fraction::new(15, 8),
];

/// Twenty-two-tone Indian scale ratios.
///
/// Derived from `indian.scl` in music21's Scala archive: Indian shruti scale
pub const INDIAN_SCALE_22: [Fraction; 22] = [
    Fraction::new(1, 1),
    Fraction::new(256, 243),
    Fraction::new(16, 15),
    Fraction::new(10, 9),
    Fraction::new(9, 8),
    Fraction::new(32, 27),
    Fraction::new(6, 5),
    Fraction::new(5, 4),
    Fraction::new(81, 64),
    Fraction::new(4, 3),
    Fraction::new(27, 20),
    Fraction::new(45, 32),
    Fraction::new(729, 512),
    Fraction::new(3, 2),
    Fraction::new(128, 81),
    Fraction::new(8, 5),
    Fraction::new(5, 3),
    Fraction::new(27, 16),
    Fraction::new(16, 9),
    Fraction::new(9, 5),
    Fraction::new(15, 8),
    Fraction::new(243, 128),
];

/// Twelve-tone quarter-comma meantone temperament (Aaron, 1523).
///
/// Derived from `meanquar.scl` in music21's Scala archive: 1/4-comma meantone scale. Pietro Aaron's temp. (1523). 6/5 beats twice 3/2
pub const QUARTER_COMMA_MEANTONE: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new_with_base(76049, 1200000, 2),
    Fraction::new_with_base(3219281, 20000000, 2),
    Fraction::new_with_base(10342157, 40000000, 2),
    Fraction::new_with_base(38631371, 120000000, 2),
    Fraction::new_with_base(16780719, 40000000, 2),
    Fraction::new_with_base(57947057, 120000000, 2),
    Fraction::new_with_base(23219281, 40000000, 2),
    Fraction::new_with_base(77262743, 120000000, 2),
    Fraction::new_with_base(29657843, 40000000, 2),
    Fraction::new_with_base(16780719, 20000000, 2),
    Fraction::new_with_base(54144607, 60000000, 2),
];

/// Twelve-tone Werckmeister III well temperament (1681).
///
/// Derived from `werck3.scl` in music21's Scala archive: Andreas Werckmeister's temperament III (the most famous one, 1681)
pub const WERCKMEISTER_III: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new(256, 243),
    Fraction::new_with_base(3203, 20000, 2),
    Fraction::new(32, 27),
    Fraction::new_with_base(5203, 16000, 2),
    Fraction::new(4, 3),
    Fraction::new(1024, 729),
    Fraction::new_with_base(23203, 40000, 2),
    Fraction::new(128, 81),
    Fraction::new_with_base(88826999, 120000000, 2),
    Fraction::new(16, 9),
    Fraction::new_with_base(18203, 20000, 2),
];

/// Twelve-tone Rameau modified meantone temperament (1725).
///
/// Derived from `rameau.scl` in music21's Scala archive: Rameau's modified meantone temperament (1725)
pub const RAMEAU: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new_with_base(14467, 200000, 2),
    Fraction::new_with_base(193157, 1200000, 2),
    Fraction::new_with_base(1489, 6000, 2),
    Fraction::new(5, 4),
    Fraction::new_with_base(251711, 600000, 2),
    Fraction::new_with_base(194949, 400000, 2),
    Fraction::new_with_base(348289, 600000, 2),
    Fraction::new_with_base(262919, 400000, 2),
    Fraction::new_with_base(177947, 240000, 2),
    Fraction::new_with_base(1006843, 1200000, 2),
    Fraction::new_with_base(90241, 100000, 2),
];

/// Twelve-tone Kirnberger III well temperament (1744).
///
/// Derived from `kirnberger3.scl` in music21's Scala archive: Kirnberger 3: 1/4 synt. comma (1744)
pub const KIRNBERGER_III: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new(135, 128),
    Fraction::new_with_base(3219281, 20000000, 2),
    Fraction::new(32, 27),
    Fraction::new(5, 4),
    Fraction::new(4, 3),
    Fraction::new(45, 32),
    Fraction::new_with_base(23219281, 40000000, 2),
    Fraction::new(405, 256),
    Fraction::new_with_base(29657843, 40000000, 2),
    Fraction::new(16, 9),
    Fraction::new(15, 8),
];

/// Twelve-tone Vallotti well temperament (c. 1754).
///
/// Derived from `vallotti.scl` in music21's Scala archive: Vallotti & Young scale (Vallotti version)
pub const VALLOTTI: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new_with_base(18827, 240000, 2),
    Fraction::new_with_base(19609, 120000, 2),
    Fraction::new_with_base(59609, 240000, 2),
    Fraction::new_with_base(19609, 60000, 2),
    Fraction::new_with_base(100391, 240000, 2),
    Fraction::new_with_base(29609, 60000, 2),
    Fraction::new_with_base(139609, 240000, 2),
    Fraction::new_with_base(79609, 120000, 2),
    Fraction::new_with_base(59609, 80000, 2),
    Fraction::new_with_base(5, 6, 2),
    Fraction::new_with_base(43609, 48000, 2),
];

/// Twelve-tone Thomas Young well temperament no. 2 (1799).
///
/// Derived from `young2.scl` in music21's Scala archive: Thomas Young well temperament no.2 (1799)
pub const YOUNG_II: [Fraction; 12] = [
    Fraction::new(1, 1),
    Fraction::new_with_base(18827, 240000, 2),
    Fraction::new_with_base(19609, 120000, 2),
    Fraction::new_with_base(59609, 240000, 2),
    Fraction::new_with_base(19609, 60000, 2),
    Fraction::new_with_base(5, 12, 2),
    Fraction::new_with_base(29609, 60000, 2),
    Fraction::new_with_base(139609, 240000, 2),
    Fraction::new_with_base(79609, 120000, 2),
    Fraction::new_with_base(59609, 80000, 2),
    Fraction::new_with_base(5, 6, 2),
    Fraction::new_with_base(18203, 20000, 2),
];
