// @generated by `cargo run --release -p xtask -- emit-tuning-tables`.
// Source of truth: data/tuning_tables.toml. Do not edit by hand.

use super::Ratio;

/// Twelve-tone harmonic-series scale (Wendy Carlos's Harmonic).
///
/// Derived from `carlos_harm.scl` in music21's Scala archive: Carlos Harmonic & Ben Johnston's scale of 'Blues' from Suite f.micr.piano (1977) & David Beardsley's scale of 'Science Friction'
pub const CARLOS_HARMONIC: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::new(17, 16),
    Ratio::new(9, 8),
    Ratio::new(19, 16),
    Ratio::new(5, 4),
    Ratio::new(21, 16),
    Ratio::new(11, 8),
    Ratio::new(3, 2),
    Ratio::new(13, 8),
    Ratio::new(27, 16),
    Ratio::new(7, 4),
    Ratio::new(15, 8),
];

/// Twenty-four-tone harmonic-series scale.
pub const CARLOS_HARMONIC_24: [Ratio; 24] = [
    Ratio::new(1, 1),
    Ratio::new(33, 32),
    Ratio::new(17, 16),
    Ratio::new(35, 32),
    Ratio::new(9, 8),
    Ratio::new(37, 32),
    Ratio::new(19, 16),
    Ratio::new(39, 32),
    Ratio::new(5, 4),
    Ratio::new(21, 16),
    Ratio::new(43, 32),
    Ratio::new(11, 8),
    Ratio::new(45, 32),
    Ratio::new(23, 16),
    Ratio::new(3, 2),
    Ratio::new(25, 16),
    Ratio::new(51, 32),
    Ratio::new(13, 8),
    Ratio::new(27, 16),
    Ratio::new(7, 4),
    Ratio::new(57, 32),
    Ratio::new(29, 16),
    Ratio::new(15, 8),
    Ratio::new(31, 16),
];

/// Twelve-tone Pythagorean tuning ratios.
pub const PYTHAGOREAN_TUNING: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::new(256, 243),
    Ratio::new(9, 8),
    Ratio::new(32, 27),
    Ratio::new(81, 64),
    Ratio::new(4, 3),
    Ratio::new(729, 512),
    Ratio::new(3, 2),
    Ratio::new(128, 81),
    Ratio::new(27, 16),
    Ratio::new(16, 9),
    Ratio::new(243, 128),
];

/// Twelve-tone five-limit tuning ratios.
///
/// Derived from `riley_albion.scl` in music21's Scala archive: Terry Riley's Harp of New Albion scale, inverse Malcolm's Monochord, 1/1 on C#
pub const FIVE_LIMIT: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::new(16, 15),
    Ratio::new(9, 8),
    Ratio::new(6, 5),
    Ratio::new(5, 4),
    Ratio::new(4, 3),
    Ratio::new(64, 45),
    Ratio::new(3, 2),
    Ratio::new(8, 5),
    Ratio::new(5, 3),
    Ratio::new(16, 9),
    Ratio::new(15, 8),
];

/// Twenty-nine-tone eleven-limit tuning ratios.
///
/// Derived from `partch_29.scl` in music21's Scala archive: Partch/Ptolemy 11-limit Diamond
pub const ELEVEN_LIMIT: [Ratio; 29] = [
    Ratio::new(1, 1),
    Ratio::new(12, 11),
    Ratio::new(11, 10),
    Ratio::new(10, 9),
    Ratio::new(9, 8),
    Ratio::new(8, 7),
    Ratio::new(7, 6),
    Ratio::new(6, 5),
    Ratio::new(11, 9),
    Ratio::new(5, 4),
    Ratio::new(14, 11),
    Ratio::new(9, 7),
    Ratio::new(4, 3),
    Ratio::new(11, 8),
    Ratio::new(7, 5),
    Ratio::new(10, 7),
    Ratio::new(16, 11),
    Ratio::new(3, 2),
    Ratio::new(14, 9),
    Ratio::new(11, 7),
    Ratio::new(8, 5),
    Ratio::new(18, 11),
    Ratio::new(5, 3),
    Ratio::new(12, 7),
    Ratio::new(7, 4),
    Ratio::new(16, 9),
    Ratio::new(9, 5),
    Ratio::new(20, 11),
    Ratio::new(11, 6),
];

/// Forty-three-tone tuning ratios.
///
/// Derived from `partch_43.scl` in music21's Scala archive: Harry Partch's 43-tone pure scale
pub const FORTY_THREE_TONE: [Ratio; 43] = [
    Ratio::new(1, 1),
    Ratio::new(81, 80),
    Ratio::new(33, 32),
    Ratio::new(21, 20),
    Ratio::new(16, 15),
    Ratio::new(12, 11),
    Ratio::new(11, 10),
    Ratio::new(10, 9),
    Ratio::new(9, 8),
    Ratio::new(8, 7),
    Ratio::new(7, 6),
    Ratio::new(32, 27),
    Ratio::new(6, 5),
    Ratio::new(11, 9),
    Ratio::new(5, 4),
    Ratio::new(14, 11),
    Ratio::new(9, 7),
    Ratio::new(21, 16),
    Ratio::new(4, 3),
    Ratio::new(27, 20),
    Ratio::new(11, 8),
    Ratio::new(7, 5),
    Ratio::new(10, 7),
    Ratio::new(16, 11),
    Ratio::new(40, 27),
    Ratio::new(3, 2),
    Ratio::new(32, 21),
    Ratio::new(14, 9),
    Ratio::new(11, 7),
    Ratio::new(8, 5),
    Ratio::new(18, 11),
    Ratio::new(5, 3),
    Ratio::new(27, 16),
    Ratio::new(12, 7),
    Ratio::new(7, 4),
    Ratio::new(16, 9),
    Ratio::new(9, 5),
    Ratio::new(20, 11),
    Ratio::new(11, 6),
    Ratio::new(15, 8),
    Ratio::new(40, 21),
    Ratio::new(64, 33),
    Ratio::new(160, 81),
];

/// Ptolemy's intense diatonic, also Zarlino's just major scale.
///
/// Derived from `ptolemy.scl` in music21's Scala archive: Intense Diatonic Syntonon, also Zarlino's scale
pub const PTOLEMY_INTENSE_DIATONIC: [Ratio; 7] = [
    Ratio::new(1, 1),
    Ratio::new(9, 8),
    Ratio::new(5, 4),
    Ratio::new(4, 3),
    Ratio::new(3, 2),
    Ratio::new(5, 3),
    Ratio::new(15, 8),
];

/// Alternate seven-tone Indian scale ratios.
///
/// Derived from `indian-sagrama.scl` in music21's Scala archive: Indian mode Sa-grama (Sa Ri Ga Ma Pa Dha Ni Sa), inverse of Didymus' diatonic
pub const INDIA_SCALE_ALT: [Ratio; 7] = [
    Ratio::new(1, 1),
    Ratio::new(9, 8),
    Ratio::new(5, 4),
    Ratio::new(4, 3),
    Ratio::new(3, 2),
    Ratio::new(27, 16),
    Ratio::new(15, 8),
];

/// Twenty-two-tone Indian scale ratios.
///
/// Derived from `indian.scl` in music21's Scala archive: Indian shruti scale
pub const INDIAN_SCALE_22: [Ratio; 22] = [
    Ratio::new(1, 1),
    Ratio::new(256, 243),
    Ratio::new(16, 15),
    Ratio::new(10, 9),
    Ratio::new(9, 8),
    Ratio::new(32, 27),
    Ratio::new(6, 5),
    Ratio::new(5, 4),
    Ratio::new(81, 64),
    Ratio::new(4, 3),
    Ratio::new(27, 20),
    Ratio::new(45, 32),
    Ratio::new(729, 512),
    Ratio::new(3, 2),
    Ratio::new(128, 81),
    Ratio::new(8, 5),
    Ratio::new(5, 3),
    Ratio::new(27, 16),
    Ratio::new(16, 9),
    Ratio::new(9, 5),
    Ratio::new(15, 8),
    Ratio::new(243, 128),
];

/// Twelve-tone quarter-comma meantone temperament (Aaron, 1523).
///
/// Derived from `meanquar.scl` in music21's Scala archive: 1/4-comma meantone scale. Pietro Aaron's temp. (1523). 6/5 beats twice 3/2
pub const QUARTER_COMMA_MEANTONE: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 76049, 1200000),
    Ratio::root(2, 3219281, 20000000),
    Ratio::root(2, 10342157, 40000000),
    Ratio::root(2, 38631371, 120000000),
    Ratio::root(2, 16780719, 40000000),
    Ratio::root(2, 57947057, 120000000),
    Ratio::root(2, 23219281, 40000000),
    Ratio::root(2, 77262743, 120000000),
    Ratio::root(2, 29657843, 40000000),
    Ratio::root(2, 16780719, 20000000),
    Ratio::root(2, 54144607, 60000000),
];

/// Twelve-tone Werckmeister III well temperament (1681).
///
/// Derived from `werck3.scl` in music21's Scala archive: Andreas Werckmeister's temperament III (the most famous one, 1681)
pub const WERCKMEISTER_III: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::new(256, 243),
    Ratio::root(2, 3203, 20000),
    Ratio::new(32, 27),
    Ratio::root(2, 5203, 16000),
    Ratio::new(4, 3),
    Ratio::new(1024, 729),
    Ratio::root(2, 23203, 40000),
    Ratio::new(128, 81),
    Ratio::root(2, 88826999, 120000000),
    Ratio::new(16, 9),
    Ratio::root(2, 18203, 20000),
];

/// Twelve-tone Rameau modified meantone temperament (1725).
///
/// Derived from `rameau.scl` in music21's Scala archive: Rameau's modified meantone temperament (1725)
pub const RAMEAU: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 14467, 200000),
    Ratio::root(2, 193157, 1200000),
    Ratio::root(2, 1489, 6000),
    Ratio::new(5, 4),
    Ratio::root(2, 251711, 600000),
    Ratio::root(2, 194949, 400000),
    Ratio::root(2, 348289, 600000),
    Ratio::root(2, 262919, 400000),
    Ratio::root(2, 177947, 240000),
    Ratio::root(2, 1006843, 1200000),
    Ratio::root(2, 90241, 100000),
];

/// Twelve-tone Kirnberger III well temperament (1744).
///
/// Derived from `kirnberger3.scl` in music21's Scala archive: Kirnberger 3: 1/4 synt. comma (1744)
pub const KIRNBERGER_III: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::new(135, 128),
    Ratio::root(2, 3219281, 20000000),
    Ratio::new(32, 27),
    Ratio::new(5, 4),
    Ratio::new(4, 3),
    Ratio::new(45, 32),
    Ratio::root(2, 23219281, 40000000),
    Ratio::new(405, 256),
    Ratio::root(2, 29657843, 40000000),
    Ratio::new(16, 9),
    Ratio::new(15, 8),
];

/// Twelve-tone Vallotti well temperament (c. 1754).
///
/// Derived from `vallotti.scl` in music21's Scala archive: Vallotti & Young scale (Vallotti version)
pub const VALLOTTI: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 18827, 240000),
    Ratio::root(2, 19609, 120000),
    Ratio::root(2, 59609, 240000),
    Ratio::root(2, 19609, 60000),
    Ratio::root(2, 100391, 240000),
    Ratio::root(2, 29609, 60000),
    Ratio::root(2, 139609, 240000),
    Ratio::root(2, 79609, 120000),
    Ratio::root(2, 59609, 80000),
    Ratio::root(2, 5, 6),
    Ratio::root(2, 43609, 48000),
];

/// Twelve-tone Thomas Young well temperament no. 2 (1799).
///
/// Derived from `young2.scl` in music21's Scala archive: Thomas Young well temperament no.2 (1799)
pub const YOUNG_II: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 18827, 240000),
    Ratio::root(2, 19609, 120000),
    Ratio::root(2, 59609, 240000),
    Ratio::root(2, 19609, 60000),
    Ratio::root(2, 5, 12),
    Ratio::root(2, 29609, 60000),
    Ratio::root(2, 139609, 240000),
    Ratio::root(2, 79609, 120000),
    Ratio::root(2, 59609, 80000),
    Ratio::root(2, 5, 6),
    Ratio::root(2, 18203, 20000),
];

/// Twelve-tone third-comma meantone temperament (Salinas, 1577).
///
/// Derived from `meanthird.scl` in music21's Scala archive: 1/3-comma meantone scale (Salinas)
pub const THIRD_COMMA_MEANTONE: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 3175183, 60000000),
    Ratio::root(2, 296207, 1875000),
    Ratio::new(6, 5),
    Ratio::root(2, 2527633, 8000000),
    Ratio::root(2, 1578793, 3750000),
    Ratio::new(25, 18),
    Ratio::root(2, 2171207, 3750000),
    Ratio::root(2, 2527633, 4000000),
    Ratio::new(5, 3),
    Ratio::root(2, 1578793, 1875000),
    Ratio::root(2, 107393119, 120000000),
];

/// Twelve-tone sixth-comma meantone temperament (Salinas, 1577).
///
/// Derived from `meansixth.scl` in music21's Scala archive: 1/6-comma meantone scale (tritonic temperament of Salinas)
pub const SIXTH_COMMA_MEANTONE: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 8859433, 120000000),
    Ratio::root(2, 4918531, 30000000),
    Ratio::root(2, 5081469, 20000000),
    Ratio::root(2, 4918531, 15000000),
    Ratio::root(2, 25081469, 60000000),
    Ratio::new(45, 32),
    Ratio::root(2, 34918531, 60000000),
    Ratio::root(2, 5246433, 8000000),
    Ratio::root(2, 14918531, 20000000),
    Ratio::root(2, 25081469, 30000000),
    Ratio::root(2, 10918531, 12000000),
];

/// Twelve-tone Werckmeister IV well temperament (1681).
///
/// Derived from `werck4.scl` in music21's Scala archive: Andreas Werckmeister's temperament IV
pub const WERCKMEISTER_IV: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 2746833, 40000000),
    Ratio::root(2, 19609, 120000),
    Ratio::new(32, 27),
    Ratio::root(2, 19609, 60000),
    Ratio::new(4, 3),
    Ratio::new(1024, 729),
    Ratio::root(2, 138827, 240000),
    Ratio::root(2, 26145333, 40000000),
    Ratio::root(2, 35609, 48000),
    Ratio::root(2, 100391, 120000),
    Ratio::new(4096, 2187),
];

/// Twelve-tone Werckmeister V well temperament (1681).
///
/// Derived from `werck5.scl` in music21's Scala archive: Andreas Werckmeister's temperament V
pub const WERCKMEISTER_V: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 3203, 40000),
    Ratio::new(9, 8),
    Ratio::root(2, 1, 4),
    Ratio::root(2, 13203, 40000),
    Ratio::root(2, 16797, 40000),
    Ratio::root(2, 1, 2),
    Ratio::new(3, 2),
    Ratio::new(128, 81),
    Ratio::root(2, 3, 4),
    Ratio::root(2, 66797, 80000),
    Ratio::root(2, 73203, 80000),
];

/// Twelve-tone Kirnberger I well temperament (1766).
///
/// Derived from `kirnberger1.scl` in music21's Scala archive: Kirnberger's temperament 1 (1766)
pub const KIRNBERGER_I: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::new(256, 243),
    Ratio::new(9, 8),
    Ratio::new(32, 27),
    Ratio::new(5, 4),
    Ratio::new(4, 3),
    Ratio::new(45, 32),
    Ratio::new(3, 2),
    Ratio::new(128, 81),
    Ratio::root(2, 111889, 150000),
    Ratio::new(16, 9),
    Ratio::new(15, 8),
];

/// Twelve-tone Neidhardt I well temperament (1724).
///
/// Derived from `neidhardt1.scl` in music21's Scala archive: Neidhardt I temperament (1724)
pub const NEIDHARDT_I: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 18827, 240000),
    Ratio::root(2, 19609, 120000),
    Ratio::root(2, 29609, 120000),
    Ratio::root(2, 19609, 60000),
    Ratio::new(4, 3),
    Ratio::root(2, 29609, 60000),
    Ratio::root(2, 139609, 240000),
    Ratio::root(2, 79609, 120000),
    Ratio::root(2, 59609, 80000),
    Ratio::new(16, 9),
    Ratio::root(2, 18203, 20000),
];

/// Twelve-tone Gottfried Silbermann temperament no. 1 (c. 1730).
///
/// Derived from `silbermann1.scl` in music21's Scala archive: Gottfried Silbermann's temperament nr. 1
pub const SILBERMANN: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 8729249, 120000000),
    Ratio::root(2, 1, 6),
    Ratio::root(2, 15391, 60000),
    Ratio::root(2, 5203, 16000),
    Ratio::root(2, 201173, 480000),
    Ratio::root(2, 23609, 48000),
    Ratio::root(2, 7, 12),
    Ratio::root(2, 26145333, 40000000),
    Ratio::root(2, 71609, 96000),
    Ratio::root(2, 201173, 240000),
    Ratio::root(2, 43609, 48000),
];

/// Twelve-tone Lehman-Bach temperament (2005).
///
/// Derived from `lehman-bach.scl` in music21's Scala archive: Brad Lehman's Bach squiggle keyboard temperament (2005)
pub const LEHMAN_BACH: [Ratio; 12] = [
    Ratio::new(1, 1),
    Ratio::root(2, 19609, 240000),
    Ratio::root(2, 19609, 120000),
    Ratio::root(2, 59609, 240000),
    Ratio::root(2, 19609, 60000),
    Ratio::root(2, 100391, 240000),
    Ratio::root(2, 59609, 120000),
    Ratio::root(2, 139609, 240000),
    Ratio::root(2, 53203, 80000),
    Ratio::root(2, 59609, 80000),
    Ratio::root(2, 199609, 240000),
    Ratio::root(2, 218827, 240000),
];
