[package]
authors = ["hill <hill@hilll.dev>"]
description = "crate for sharing code between test suite and build script"
edition = "2021"
license-file = "../LICENSE"
name = "utils"
repository = "https://github.com/float3/music21-rs"

[features]
default = ["python"]
python = ["dep:pyo3", "dep:reqwest"]

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"], optional = true }
pyo3 = { version = "0.23.4", features = ["auto-initialize"], optional = true }
