//! The reports page's script: TypeScript in, JavaScript out.
//!
//! Everything scripted in this repository is written in TypeScript — the four
//! web demos are, and so is this. A browser cannot run TypeScript, and the
//! report page carries its script inline so that the page is one
//! self-contained file, so `report/html.rs` reaches for the compiled JavaScript
//! with `include_str!` at build time.
//!
//! That is why the compiled `report.js` is committed rather than built: an
//! `include_str!` has to find a file the moment cargo builds `xtask`, and
//! `xtask` is built by CI's lint job, by every `cargo check` of the
//! workspace, and by anyone who has never installed Node. Making all of those
//! depend on a TypeScript compiler to build a 77-line script would be a poor
//! trade. So this takes the shape every other generated file here has: the
//! source is `report.ts`, the generated file beside it is committed, `emit`
//! writes it and `verify` asserts the two agree.

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The TypeScript the whole repository compiles with. `examples/web`'s
/// `package.json` pins the same one; the two are meant to match, so that the
/// report's script and the demos' are not built by different compilers.
const TYPESCRIPT: &str = "typescript@5.9.3";

/// The banner the emitted file carries, so that a reader who opens it knows
/// it is not the thing to edit.
const BANNER: &str = "\
// Generated by `cargo run --release -p xtask -- emit-report-script` from
// report.ts beside this file. Do not edit; edit the TypeScript and re-emit.
";

/// The TypeScript the page's script is written in.
pub fn source_path(workspace_root: &Path) -> PathBuf {
    workspace_root.join("xtask/src/report.ts")
}

/// The JavaScript the page carries, which `report/html.rs` includes.
pub fn generated_path(workspace_root: &Path) -> PathBuf {
    workspace_root.join("xtask/src/report.js")
}

/// Compiles `report.ts` and answers the JavaScript, writing nothing that
/// anyone tracks.
///
/// Both `emit` and `verify` come through here, so that what is checked is
/// exactly what would be written.
pub fn compile(workspace_root: &Path) -> Result<String, Box<dyn Error>> {
    let source = source_path(workspace_root);
    if !source.is_file() {
        return Err(format!("{} is missing", source.display()).into());
    }
    let out_dir = workspace_root.join(format!("target/xtask/report-script-{}", std::process::id()));
    let _ = fs::remove_dir_all(&out_dir);
    fs::create_dir_all(&out_dir)?;
    let result = run_tsc(workspace_root, &out_dir).and_then(|()| {
        let emitted = out_dir.join("report.js");
        fs::read_to_string(&emitted)
            .map_err(|err| format!("tsc wrote no {} ({err})", emitted.display()).into())
    });
    let _ = fs::remove_dir_all(&out_dir);
    Ok(format!("{BANNER}{}", normalised(&result?)))
}

/// Writes the compiled script beside its source.
pub fn emit(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let javascript = compile(workspace_root)?;
    let path = generated_path(workspace_root);
    fs::write(&path, &javascript)?;
    println!(
        "{} lines of JavaScript emitted at {}",
        javascript.lines().count(),
        path.display()
    );
    Ok(())
}

/// Fails when the committed JavaScript is not what the TypeScript compiles to.
pub fn verify(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let expected = compile(workspace_root)?;
    let path = generated_path(workspace_root);
    let actual = fs::read_to_string(&path)
        .map_err(|err| format!("{} is unreadable ({err})", path.display()))?;
    if normalised(&actual) != expected {
        return Err(format!(
            "{} is out of date; run `cargo run --release -p xtask -- emit-report-script`",
            path.display()
        )
        .into());
    }
    println!(
        "Committed {} matches {}",
        path.display(),
        source_path(workspace_root).display()
    );
    Ok(())
}

/// Line endings as the repository stores them.
///
/// `.gitattributes` checks every text file out with LF and `tsconfig.json`
/// asks tsc for LF, but a file that has been through an editor on Windows can
/// still be sitting on disk with CRLF. Comparing that against a fresh compile
/// would fail for a reason that has nothing to do with the script.
fn normalised(text: &str) -> String {
    text.replace("\r\n", "\n")
}

/// Runs the pinned TypeScript compiler over `xtask/tsconfig.json`.
fn run_tsc(workspace_root: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let project = workspace_root.join("xtask/tsconfig.json");
    let mut last: Option<String> = None;
    // Windows resolves `npx` to `npx.cmd`, which `Command` will not find
    // under the bare name, so the names are tried in turn.
    for program in npx_names() {
        let output = Command::new(program)
            .current_dir(workspace_root)
            .args(["--yes", "--package", TYPESCRIPT, "tsc", "--project"])
            .arg(&project)
            .arg("--outDir")
            .arg(out_dir)
            .output();
        match output {
            Err(err) => last = Some(format!("could not run {program} ({err})")),
            Ok(output) if output.status.success() => return Ok(()),
            Ok(output) => {
                let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
                text.push_str(&String::from_utf8_lossy(&output.stderr));
                return Err(format!("tsc failed:\n{}", text.trim()).into());
            }
        }
    }
    Err(format!(
        "{}; Node.js and npx are needed to compile {}",
        last.unwrap_or_else(|| "npx is not installed".to_string()),
        source_path(workspace_root).display()
    )
    .into())
}

fn npx_names() -> &'static [&'static str] {
    if cfg!(windows) {
        &["npx.cmd", "npx"]
    } else {
        &["npx"]
    }
}
