! Septimal JI
!
13-tone Septimal Just Intonation: a 7-limit Rational Intonation scale, consisting of 13 notes per 3/2 derived from harmonic series intervals up to a prime limit of 7. The pattern chosen takes all complete and gapless harmonic and subharmonic divisions of the perfect fifth and perfect fourth within the 23 limit and compiles notes which occur in at least two such divisions. The division of the fifth and two symmetrically placed divisions of the fourth are superposed.
13
!
16/15
15/14
9/8
8/7
7/6
6/5
5/4
9/7
21/16
4/3
7/5
45/32
3/2
